### ISSUE TITLE
[1.12.2] Custom bees from Gendustry are not recognized.

### ISSUE THREAD

**Issue by kekvitirae** [SenilePenguin/BQ-Forestry#15]
Please ensure that the report you are about to submit does not already exist (use the search!).

**Version Information**
 - Minecraft [e.g. 1.12.2]: 1.12.2
 - Forge [e.g. 14.23.5.2768]: 14.23.5.2847
 - BQ Forestry [e.g. 1.0.1]: 2.0.0

**Describe the bug**
During a Bee Retrieval Task edit, custom bees can be searched for as normal, but once they are selected the Species reads **(MISSING) gendustry.bee.<bee name> (gendustry.bee.<bee name>)** in red font, using the default Common Bee as the graphic. This Bee Retrieval Task will never recognize the custom bee in any way as a player.

https://i.imgur.com/3K2j6dN.png

**Comment by SenilePenguin** [comment]
Note: Some of these notes may be gibberish to you. They are also for me to keep up with my findings. A response is not required.

The issues appears to be caused by Gendustry registering it's bees under Forestry's MODID, which is causing them to be parsed incorrectly. The reason for the names to be showing properly in the right-side searchable list is due to that reading the "..getAlleleName()" property of the trait, while the left-side information pane is trying to get the actual name from the bee itself, using "..getDisplayName()". This is causing an error due to Gendustry not overriding that method for it's custom bees on the stack. On a similar thread, the wrong icon is also displayed in the top-scrolling-list area as a result of not having the itemstack properly overridden. I think this is a bug within Gendustry itself (especially the part where it registers bees under Forestry's MODID), but as it doesn't seem to be receiving updates anymore, I'm going to see if there's any way to access the needed information from within my code. Sit tight.

**Comment by SenilePenguin** [comment]
I believe this issue has been resolved now. I've tested the mod to work with all of the popular 1.12.2 bee mods I could locate, including: Bennie's Mods, Career Bees, Magical Bees, Extra Bees, More Bees, Equivalent Bees, Gendustry, and of course the stock Forestry bees. All species seem to be functional for submitting and creating tasks for now. I've fixed a few other bugs along the way as well, if you'd like to download the newest release, 2.1.0,  from CurseForge and give it a whirl! If you do happen to stumble on any problems with it, you're more than welcome to re-open this issue.
